services:
  db:
    image: postgres:16
    container_name: codestash-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: codestash
    ports:
      - "5437:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 3s
      timeout: 5s
      retries: 5

  migrate:
    image: postgres:16
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migration/versions:/migrations:ro
    entrypoint: >
      sh -c '
      for f in /migrations/*.sql; do
        psql postgres://root:password@db:5432/codestash -f "$${f}";
      done
      '

volumes:
  postgres-data: