// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/k-kanke/code-stash-server/internal/adapter/controller"
	"github.com/k-kanke/code-stash-server/internal/infra/repository"
	"github.com/k-kanke/code-stash-server/internal/usecase/collection"
	"github.com/k-kanke/code-stash-server/internal/usecase/folder"
	"github.com/k-kanke/code-stash-server/internal/usecase/note"
)

import (
	_ "github.com/jackc/pgx/v5/stdlib"
)

// Injectors from wire.go:

func InitializeHandler(db *sql.DB) (*controller.Handler, error) {
	collectionRepository := repository.NewCollectionPGRepository(db)
	usecase := collection.NewUsecase(collectionRepository)
	folderRepository := repository.NewFolderPGRepository(db)
	folderUsecase := folder.NewUsecase(folderRepository)
	noteRepository := repository.NewNotePGRepository(db)
	noteUsecase := note.NewUsecase(noteRepository)
	dependencies := controller.Dependencies{
		Collections: usecase,
		Folders:     folderUsecase,
		Notes:       noteUsecase,
	}
	handler := controller.NewHandler(dependencies)
	return handler, nil
}
